name: Reusable workflow example

on:
  workflow_call:

jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sleep 10
        ls -l /
    - run: echo finnish

  step2:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sleep 15
        ls -l /home/
    - run: echo finnish2
